[project]
name = "call666"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llm-sdk",
    "pydantic>=2.13.4",
]

[tool.uv.sources]
llm-sdk = { path = "llm_sdk" }

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=2.3.1",
]
